---
version: '2.3'

services:
  train:
    #image: nvcr.io/nvidia/pytorch:20.06-py3
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia
    volumes:
      - .:/yolo
      - /mnt/NAS/Production/TruckBay/:/mnt/NAS/Production/TruckBay
      - /mnt/NAS/Public/parque_research/datasets/coco_yolo/coco:/mnt/coco
      - /home/kweston/darknet_utils:/home/kweston/darknet_utils
      - /home/kweston/speedco/baywatchr-inference/speedco_dataset:/mnt/speedco_dataset
      - /home/kweston/speedco/baywatchr-inference/data/lists:/mnt/speedco_datalists
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/baywatchr-api-key.json
    command: 
      - bash
    shm_size: 64g
